# config/application.yml
defaults: &defaults

  api:
    url : "https://beta.openphacts.org/2.1" #eg https://beta.openphacts.org remember to include the api version if available. ie https://beta.openphacts.org/1.5
    ebi_smiles_to_ctab: "https://www.ebi.ac.uk/chembl/api/utils/smiles2ctab" # used to convert smiles to mol for ketcher

  keys:
    app_id: "85864658" #app id from https://dev.openphacts.org
    app_key: "6238f59d62078ba2d6152fc8bf6afe68" #app key from https://dev.openphacts.org

  tsv:
    api_version: "1.3" # this only works for 1.3 on, 1.2 cannot handle the /1.2 verison number bit, however it can be empty ie "" if required
    url: "beta.openphacts.org" # no protocol eg beta.openphacts.org 
    target_path : "/target/pharmacology/pages" # or equivalent for target pharma paginated
    compound_path: "/compound/pharmacology/pages" # or equivalent for compound pharma paginated
    tree_path: "/target/tree/pharmacology/pages" # or equivalent for target class pharma paginated
    tree_compound_path: "/compound/tree/pharmacology/pages" # for compound class pharma

  maintenance: FALSE

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
